### ISSUE TITLE
Change values from the example that I gave you

### ISSUE THREAD

**Issue by nandanrao** [escola-nova/RTT-logstash#1]
@marcoantonioghiani01 -

So the problem with your logstash config was that you didn't actually change anything. 

The field "service_account" needs to be changed to reflect the service account you are actually using! Similarly, the "bucket" will need to be changed, as you won't put it in the same bucket, nor will the service account have access to the bucket from someone else's example!

Similarly, all the configuration of the "pubsub" needs to reflect your actual pubsub topic and subscription that you create. 

In general, whenever you get an example from someone you should: 

1) Read the documentation (in this case, logstash input/output documentation), and go over each item of the config to make sure you understand what it's doing, and whether or not you should change it for your use case or not. If you read the documentation, it would be very obvious that you need to change "service_account" and "bucket".

2) Always be on the lookout for things with other people's usernames or namespaces or application names in it. That probably needs to be changed! "jobboards" is clearly not a google default, nor is it a name you created, thus it probably needs to be changed.

**Comment by tonyghiani** [comment]
Oh my bad, I had some enhancements in local but still not complete.
Anyway thanks a lot for the heads up, I'll go through the doc and I'll make sure it works!

**Comment by tonyghiani** [comment]
Ok, the file is well configured now and works, it connects to the bucket I created and generate our log files.
